#include <map>

namespace manuals
{
    std::map<std::string, std::string> text = {
        {"", "Put me to the right of a cvly module!"},
        {"brst", "Module: brst\nSingle: each burst will output to a single channel, chosen randomly using the weight parameter of each channel.\nMultiple: each burst will output to multiple channels, chosen individually according to the weight.\nSequencer: each burst will move to the next sequential channel. In this mode, weight is the chance that the burst will actually move to the next channel.\nChannels with weight equal to 0 are inactive.\nTime between bursts is controlled by the time and var parameters, with time being the base, and var the variation in percentage.\nThe CV output of each channel can be set to Sample & Hold or pass-thru from the CV input."},
        {"bss", "Module: bss\nAttempts to find a bass note for an incoming chord. It has three modes: Harmonic, Lowest and Random.\nIn Harmonic mode, it analyses the intervals between the chord notes, and then tries to choose the best root note based on that. This is a work in progress still, any feedback is appreciated.\nThe Oct and Note parameters are used to specify what is the lowest note that the module will output, and any other notes are put up to an octave above that note."},
        {"crcl", "Module: crcl\nMode 1: Quantizer for the voltage coming through the CV input. If the trigger input is connected, it will also act as a Sample & Hold.\n\nMode 2: Sequencer, receiving the clock in the trigger input, and ciclying through the circle of fifths. The output CV is kept inside one octave from the root.\nThe CV input can be used to reverse the direction of the sequence:\n0v or higher: clockwise.\nLower than 0v: counter-clockwise.\n\nMode 3: Exactly like mode 1, except that after quantizing the input signal, it will output the mirror note using the line between the tonic and the fifth as axis. Based on the music theory concept of Negative harmony."},
        {"ntrvlc", "Module: ntrvlc\nFour 8-step sequences with an incorporated equi-likely quantizer. Each of the four sequences has an independent clock input and a separate output, along with a common polyphonic output. Only sequences with a connected clock input will be sent to the poly out.\nIf the quantizer does not have any notes active, the module will output raw voltage.\nVoltage range can be set in the context menu.\n\nIf the stack button is on, the first active sequencer will work normally, but each subsequent sequence will be built on top of the last one, adding or subtracting from the previous voltage. If it's off, each sequencer will function independently."},
        {"ntrvlx", "Module: ntrvlx\n'Weight' attenuates the base CV before adding, so at 1 it works the same as without the expander, and at 0 is the same as stacking off.\n'Snap' makes it so that each output is within the selected voltage range when stacking, taking weight into account:\nOUTn = ((CVn-1 * weight) + CVn) / (1 + weight)\nIt also adds 4 triggers, one for each sequence, that fire whenever the output of its sequence changes. Option to turn first output to poly in the context menu."},
        {"spc", "Module: spc\nSpreads an incoming chord using a settable minimum interval distance between notes.\nThe Oct and Note parameters sets which is the lowest note that the module will output.\n\nFor example, for polyphonic input D5 D4 G3 A5 D3, if the minimum distance is set to 3 semitones and lowest note is set as C1, the output will be D1 D2 G2 A3 D4.\nAn option in the right click menu can be turned on to sort the input before spreading, so for the same case above, the input will be sorted first to D3 G3 D4 A5 D5, and the output will be D1 G1 D2 A2 D3."},
        {"stpr", "Module: stpr\nA 8-step sequencer. Each step can be activated or deactivated using its trigger input. When the module receives a clock signal, it looks for the next active step, and moves to it. If no step is active, it will remain in the current step (regardless of its active status).\nVoltage range can be set in the context menu."},
        {"txt", "Recursion (adjective: recursive) occurs when a thing is defined in terms of itself or of its type. Recursion is used in a variety of disciplines ranging from linguistics to logic. The most common application of recursion is in mathematics and computer science, where a function being defined is applied within its own definition. While this apparently defines an infinite number of instances (function values), it is often done in such a way that no infinite loop or infinite chain of references can occur."},
        {"vbrt", "Each row has:\n* Input for pitch (1v/oct), normalized to the previous input.\n* Range of detuning in cents (both up and down), which will vary with the LFO.\n* Scaling input (0-10v) for the detuning amount.\n* Mirror mode will change the output into a polyphonic output with two channels, with mirrored detuning.\n* Frequency for the sine LFO (if set to 0, the channel will work like a simple detuner).\n* Switch to send the channel to the polyphonic output."},
        {"whl", "And wow! Hey! What's this thing suddenly coming towards me very fast? Very very fast. So big and flat and round, it needs a big wide sounding name like …ow …ound …round …ground! That's it! That's a good name - ground!\n\nI wonder if it will be friends with me?\n\n- Douglas Adams, The Hitchhiker's Guide to the Galaxy"}};
}